// apps/site/src/app/ui/footer.svelte
<script>
	import Link from '$lib/shared/ui/link.svelte';
	import Wrapper from '$lib/shared/ui/wrapper.svelte';
</script>

<footer class="flex items-center justify-center">
	<Wrapper class="flex items-center justify-between gap-3 py-4 pt-5 max-sm:flex-col">
		<div>
			Создатель: <Link isExternal target="_blank" href="https://github.com/reversoid"
				>reversoid</Link
			>
		</div>

		<div class="flex items-center justify-center gap-2">
			<Link target="_blank" href="https://github.com/reversoid/moofy">Github</Link>
			<Link href="/support">Поддержка</Link>
			<Link href="/about">О проекте</Link>
		</div>
	</Wrapper>
</footer>

// src/app/ui/Layout/Footer.tsx
import { Wrapper } from './Layout';
import { Text, styled, Link } from '@nextui-org/react';
import { Link as MyLink } from '@/shared/ui/Link/Link';

const Div = styled('div', {});
const PagesWrapper = styled('div', {
  display: 'flex',
  gap: '$7',
});

const LinkStyled = styled(MyLink, {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  width: 'fit-content',
  transition: 'color 0.05s linear',
  '&:hover': {
    color: '$primary',
  },
});
function Footer() {
  return (
    <Wrapper
      lg
      css={{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        pt: '$10',
        pb: '$8',
        '@xsMax': {
          flexDirection: 'column',
          gap: '$5',
          pb: '$10',
        },
      }}
    >
      <Div css={{ display: 'flex', alignItems: 'center', gap: '$3' }}>
        <Text color="$neutral">Created by</Text>{' '}
        <Link
          href="https://github.com/reversoid"
          target="_blank"
          rel="noopener noreferrer"
        >
          reversoid
        </Link>
      </Div>
      <PagesWrapper>
        <Link
          href="https://github.com/reversoid/moofy-frontend"
          target="_blank"
          rel="noopener noreferrer"
          css={{
            color: '$neutral',
            '&:hover': {
              color: '$primary',
              opacity: 1,
              transition: 'color 0.05s linear',
            },
          }}
        >
          Github
        </Link>
        <LinkStyled to="/support" css={{ color: '$neutral' }}>
          Поддержка
        </LinkStyled>
        <LinkStyled to="/help" css={{ color: '$neutral' }}>
          Помочь проекту
        </LinkStyled>
      </PagesWrapper>
    </Wrapper>
  );
}

export default Footer;
